# NumPy Arrays

Most of the computational problems in engineering involve *arrays*. We used them to describe discretized or numerical  problems. Even more arrays are useful to represent calculus operations, like derivatives or integration. 

When we computations that need to be repeated for different values, it is advantageous to represent that data as arrays and use array operations. We call this kind of computations *vectorized*. Using vectorized computations avoid using many for loops by applying operations in "batches". This behaviour results in programs that run faster than their "loop version".   

In Python the scientific computing enviornment comes with the NumPy library. This library counts with data structures and a collection of operators and functions that make more efficient the operations that involve arrays. From now on, everytime that we need to manipulate arrays/matrices operation we will work with NumPy. 


## Importing libraries

First, a word on importing libraries. To import a library we used the `import` command. For example, to import Numpy we do:

```python
import numpy
```
this load all the functions in the **NumPy** library:

Once you execute that command in a code cell, you can call any **NumPy** function by prepending the library name, e.g., `numpy.linspace()`, [`numpy.ones()`](https://docs.scipy.org/doc/numpy/reference/generated/numpy.ones.html#numpy.ones), [`numpy.zeros()`](https://docs.scipy.org/doc/numpy/reference/generated/numpy.zeros.html#numpy.zeros), [`numpy.empty()`](https://docs.scipy.org/doc/numpy/reference/generated/numpy.empty.html#numpy.empty), [`numpy.copy()`](https://docs.scipy.org/doc/numpy/reference/generated/numpy.copy.html#numpy.copy), and so on (explore the documentation for these very useful functions!).

But, you will find _a lot_ of sample code online that uses a different syntax for importing. They will do:
```python
import numpy as np
```
All this does is create an alias for `numpy` with the shorter string `np`, so you then would call a **NumPy** function like this: `np.linspace()`. This is just an alternative way of doing it, for lazy people that find it too long to type `numpy` and want to save 3 characters each time. For the not-lazy, typing `numpy` is more readable and beautiful. We like it better like this:

In [1]:
import numpy

To use one of **NumPy**'s functions, we prepend `numpy.` (with the dot) to the function name. For example, to create an array we do:

In [2]:
numpy.array([3, 5, 8, 17])

array([ 3,  5,  8, 17])

NumPy has different ways to create arrays in addition to the normal `array()`. Probably the more useful are: [`numpy.ones()`](https://docs.scipy.org/doc/numpy/reference/generated/numpy.ones.html#numpy.ones), [`numpy.zeros()`](https://docs.scipy.org/doc/numpy/reference/generated/numpy.zeros.html#numpy.zeros), [`numpy.arange()`](https://docs.scipy.org/doc/numpy/reference/generated/numpy.arange.html) and [`numpy.linspace()`](https://docs.scipy.org/doc/numpy/reference/generated/numpy.linspace.html). 

`numpy.ones()` and `numpy.zeros()` are very intuitively, they create arrays full of ones and zeros respectively. The amount of elements in the arrays are determined by the integer we pass as an argument. 

In [3]:
numpy.ones(5)

array([ 1.,  1.,  1.,  1.,  1.])

In [4]:
numpy.zeros(3)

array([ 0.,  0.,  0.])

`numpy.arange()` gives as an evenly spaced values in a defined interval. 

*Syntax:*

`numpy.arange(start, stop, step)`

where `start` by default is zero, `stop` is not inclusive, and the default
for `step` is one.  


In [5]:
numpy.arange(4)

array([0, 1, 2, 3])

In [6]:
numpy.arange(2, 6)

array([2, 3, 4, 5])

In [7]:
numpy.arange(2, 6, 2)

array([2, 4])

In [8]:
numpy.arange(2, 6, 0.5)

array([ 2. ,  2.5,  3. ,  3.5,  4. ,  4.5,  5. ,  5.5])

`numpy.linspace()` is similar to `numpy.arange()`, but uses number of samples instead of a step size. 

`numpy.linspace()` returns an array with evenly spaced numbers over the specified interval.  

*Syntax:*

`numpy.linspace(start, stop, num)`

`stop` is included by default (it can be removed, read docs) and `num` by default is 50. 

In [9]:
numpy.linspace(2.0, 3.0)

array([ 2.        ,  2.02040816,  2.04081633,  2.06122449,  2.08163265,
        2.10204082,  2.12244898,  2.14285714,  2.16326531,  2.18367347,
        2.20408163,  2.2244898 ,  2.24489796,  2.26530612,  2.28571429,
        2.30612245,  2.32653061,  2.34693878,  2.36734694,  2.3877551 ,
        2.40816327,  2.42857143,  2.44897959,  2.46938776,  2.48979592,
        2.51020408,  2.53061224,  2.55102041,  2.57142857,  2.59183673,
        2.6122449 ,  2.63265306,  2.65306122,  2.67346939,  2.69387755,
        2.71428571,  2.73469388,  2.75510204,  2.7755102 ,  2.79591837,
        2.81632653,  2.83673469,  2.85714286,  2.87755102,  2.89795918,
        2.91836735,  2.93877551,  2.95918367,  2.97959184,  3.        ])

In [10]:
len(numpy.linspace(2.0, 3.0))

50

In [11]:
numpy.linspace(2.0, 3.0, 6)

array([ 2. ,  2.2,  2.4,  2.6,  2.8,  3. ])

In [12]:
numpy.linspace(-1, 1, 9)

array([-1.  , -0.75, -0.5 , -0.25,  0.  ,  0.25,  0.5 ,  0.75,  1.  ])

Let's assign the arrays to some variables and perform some operations. 

In [13]:
x_array = numpy.linspace(-1, 1, 9)

Now, we can do some computations with the array. Like rise to the power of 2:

In [14]:
y_array = x_array**2
print(y_array)

[ 1.      0.5625  0.25    0.0625  0.      0.0625  0.25    0.5625  1.    ]


Notice that the operations of raising the `x_array` to the power of 2 returns an array where each element was raise to the power of 2.

We can also take the square root of a positive define array, using the `numpy.sqrt()` function:

In [15]:
z_array = numpy.sqrt(y_array)
print(z_array)

[ 1.    0.75  0.5   0.25  0.    0.25  0.5   0.75  1.  ]


Now we have different arrays `x_array`, `y_array` and `z_array`, we can do more computations like add or multiply them. For example:

In [16]:
add_array = x_array + y_array 
print(add_array)

[ 0.     -0.1875 -0.25   -0.1875  0.      0.3125  0.75    1.3125  2.    ]


When we add two or more arrays, their element are added element-wise. Same happens if we multiply them:

In [17]:
mult_array = x_array * z_array
print(mult_array)

[-1.     -0.5625 -0.25   -0.0625  0.      0.0625  0.25    0.5625  1.    ]


We can also divide arrays, but you have to be careful in not to divide by zero. This operation will result in a `nan` which stands for *Not a Number*. Python will still perform the division, but will tell us about the problem.  

Let's see how this look:

In [18]:
x_array / y_array

/home/ncclementi/anaconda3/lib/python3.5/site-packages/ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in true_divide
  """Entry point for launching an IPython kernel.


array([-1.        , -1.33333333, -2.        , -4.        ,         nan,
        4.        ,  2.        ,  1.33333333,  1.        ])

### Multidimension arrays

**2D arrays** 

In NumPy we can create array of N dimensions.  For example, a 2D array can be:

In [19]:
array_2d = numpy.array([[1, 2], [3, 4]])
print(array_2d)

[[1 2]
 [3 4]]


We can do operations with 2D arrays too. 

In [20]:
X = numpy.array([[1, 2], [3, 4]])
Y = numpy.array([[1, -1], [0, 1]])

The addition of these two matrices work exactly as we expect:

In [21]:
X + Y

array([[2, 1],
       [3, 5]])

What if we try to multiply using the `'*'`operator?

In [22]:
X * Y

array([[ 1, -2],
       [ 0,  4]])

The multiplication using the `'*'` operator is element-wise. If we want to a matrix multiplication we use the `'@'` operator:

In [23]:
X @ Y

array([[1, 1],
       [3, 1]])

Or equivalently we can use `numpy.dot()`:

In [24]:
numpy.dot(X, Y)

array([[1, 1],
       [3, 1]])

**3D arrays**

Let's create a 3D array by reshaping a 1D array. We can use [`numpy.reshape()`](https://docs.scipy.org/doc/numpy/reference/generated/numpy.reshape.html), where we pass the array we want to reshape and the shape we want to give. 

*Syntax*
 
`numpy.reshape(array, newshape)`

For example:

In [25]:
a = numpy.arange(24)

In [26]:
a_3D = numpy.reshape(a, (2, 3, 4))
print(a_3D)

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]


We can check for the shape of a numpy array by using the numpy function `shape()`:

In [27]:
numpy.shape(a_3D)

(2, 3, 4)

If you are confused about the dimensions of the `a_3D` array, here there is a figure that will help you to understand how the dimensions are assigned:

<img src="images/3d_array_sketch.png" style="width: 400px;"/> 


When we have multidimension arrays, we can access slices of their elements by slicing per dimension. This is on of the advantages we have when using arrays. We can not do this with lists. 

Let's access the elments of our `X` 2D array:

In [28]:
X

array([[1, 2],
       [3, 4]])

In [29]:
# Grab the 1st element of 1st column 
X[0, 0]

1

In [30]:
# Grab the 1st element of 2nd column 
X[0, 1]

2

**Exercise:** 
1. Grab the 2nd element of 1st column.
2. Grab the 2nd element of 2nd column

Now, we will do slicing on this array:

In [31]:
# Grab the 1st column
X[:, 0]

array([1, 3])

The symbol `':'` means all. In other words we are telling python that from that dimension collect all the elements.

In [32]:
# Grab the 1st row
X[0, :]

array([1, 2])

**Exercise:** 
1. Grab the 2nd column.
2. Grab the 2nd row.

Let's practice with a 3D array. 

In [33]:
a_3D

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

If we want to grab the first column of both matrices in our `a_3D` array we do:

In [34]:
a_3D[:, :, 0]

array([[ 0,  4,  8],
       [12, 16, 20]])

What we are telling python in the line above is:

* first `':'` : from the first dimension grab all the elements. (2 matrices)
* second `':'`: from the second dimension grab all the elements. (all the rows)
* `'0'`       : from the third dimension grab the first element. (first column)

If we want the first 2 elements of the first column of both matrices: 

In [35]:
a_3D[:, 0:2, 0]

array([[ 0,  4],
       [12, 16]])

From the first matrix in our `a_3D` array, we will grab the two middle elements (5,6):

In [36]:
a_3D[0, 1, 1:3]

array([5, 6])

**Exercise:** From the `a_3D` array: 
1. Grab the two middle elements (17, 18) from the second matrix.
2. Grab the last row from both matrices.
3. Grab the elements of the 1st matrix that exclude the first row and the first column. 
4. Grab the elements of the 2nd matrix that exclude the last row and the last column. 

## Numpy == Fast and Clean! 

When we are working with numbers, arrays are a better option because the NumPy library has built-in functions that are optimized, and therefore faster than vanilla Python. Specially, if we have big arrays. Besides, using NumPy arrays and exploiting their properties, make our code more readable.

For example, if we want to add element-wise the elements of 2 lists, we need to write a for loop. Meanwhile, if we want to add two NumPy arrays, we just use the addtion `'+'` symbol.


### Lists element-wise sum.

In [37]:
#import random library
import random

Using the random library we generate two random lists with 100 elements in the range [0,100), with no numbers repeated (pseudo-random)

In [38]:

lst_1 = random.sample(range(100), 100)
lst_2 = random.sample(range(100), 100)

In [39]:
#print first 10 elements
print(lst_1[0:10])
print(lst_2[0:10])

[29, 37, 11, 98, 75, 79, 38, 24, 18, 1]
[82, 49, 68, 19, 35, 21, 63, 44, 32, 93]


We have two lists of one hundred elements, we want to sum them element-wise and time this execution. We will write a for loop and append the result of the element-wise sum into a list called `result_lst`. For timing, we will use the IPython magics `%%time`. Wrting at the beginning of the cell the command `%%time` will compute the time for all the code in that cell. 

In [40]:
%%time
res_lst = []
for i in range(100):
    res_lst.append(lst_1[i] + lst_2[i])

CPU times: user 0 ns, sys: 0 ns, total: 0 ns
Wall time: 56.7 µs


In [41]:
print(res_lst[0:10])

[111, 86, 79, 117, 110, 100, 101, 68, 50, 94]


### NumPy arrays element-wise sum.

In this case to generate random arrays, we will use the NumPy function `numpy.random.randint()`. The arrays we generate with this function are not going to be like the lists, in this case we will have 100 elements that will be picked from the range [0, 100) but in this case they can be repeated. For our purpose, the only thing thata matters is that the arrays and the lists are of the same length and type (integers).

In [42]:
arr_1 = numpy.random.randint(0, 100, size=100)
arr_2 = numpy.random.randint(0, 100, size=100)

In [43]:
#print first 10 elements
print(arr_1[0:10])
print(arr_2[0:10])

[68 72  2 66 74 26 18 85 81 70]
[96 79 35 75 44 38 14 50 52 62]


In [44]:
%%time
arr_res = arr_1 + arr_2

CPU times: user 0 ns, sys: 0 ns, total: 0 ns
Wall time: 28.4 µs


Notice that in the case of arrays, the code not only is more readable (just one line of code), but it is also faster than in the case of lists. This gap in time is bigger when we increased the size of our arrays/lists. 

**Exercise:** 

1. Try the comparison between lists and arrays, using a bigger size of arrays, for example 10000. 
2. Repeat the analysis but now computing the operation that elevetas each element of an array/list to the power of two. 

In [45]:
# Execute this cell to load the notebook's style sheet, then ignore it
from IPython.core.display import HTML
css_file = '../../style/custom.css'
HTML(open(css_file, "r").read())