# NumPy Arrays

Most of the computational problems in engineering involve *arrays*. We used them to describe discretized or numerical  problems. Even more arrays are useful to represent calculus operations, like derivatives or integration. 

When we computations that need to be repeated for different values, it is advantageous to represent that data as arrays and use array operations. We call this kind of computations *vectorized*. Using vectorized computations avoid using many for loops by applying operations in "batches". This behaviour results in programs that run faster than their "loop version".   

In Python the scientific computing enviornment comes with the NumPy library. This library counts with data structures and a collection of operators and functions that make more efficient the operations that involve arrays. From now on, everytime that we need to manipulate arrays/matrices operation we will work with NumPy. 


## Importing libraries

First, a word on importing libraries. To import a library we used the `import` command. For example, to import Numpy we do:

```python
import numpy
```
this load all the functions in the **NumPy** library:

Once you execute that command in a code cell, you can call any **NumPy** function by prepending the library name, e.g., `numpy.linspace()`, [`numpy.ones()`](https://docs.scipy.org/doc/numpy/reference/generated/numpy.ones.html#numpy.ones), [`numpy.zeros()`](https://docs.scipy.org/doc/numpy/reference/generated/numpy.zeros.html#numpy.zeros), [`numpy.empty()`](https://docs.scipy.org/doc/numpy/reference/generated/numpy.empty.html#numpy.empty), [`numpy.copy()`](https://docs.scipy.org/doc/numpy/reference/generated/numpy.copy.html#numpy.copy), and so on (explore the documentation for these very useful functions!).

But, you will find _a lot_ of sample code online that uses a different syntax for importing. They will do:
```python
import numpy as np
```
All this does is create an alias for `numpy` with the shorter string `np`, so you then would call a **NumPy** function like this: `np.linspace()`. This is just an alternative way of doing it, for lazy people that find it too long to type `numpy` and want to save 3 characters each time. For the not-lazy, typing `numpy` is more readable and beautiful. We like it better like this:

In [1]:
import numpy

To use one of **NumPy**'s functions, we prepend `numpy.` (with the dot) to the function name. For example, to create an array we do:

In [3]:
numpy.array([3, 5, 8, 17])

array([ 3,  5,  8, 17])

NumPy has different ways to create arrays in addition to the normal `array()`. Probably the more useful are: [`numpy.ones()`](https://docs.scipy.org/doc/numpy/reference/generated/numpy.ones.html#numpy.ones), [`numpy.zeros()`](https://docs.scipy.org/doc/numpy/reference/generated/numpy.zeros.html#numpy.zeros), [`numpy.arange()`](https://docs.scipy.org/doc/numpy/reference/generated/numpy.arange.html) and [`numpy.linspace()`](https://docs.scipy.org/doc/numpy/reference/generated/numpy.linspace.html). 

`numpy.ones()` and `numpy.zeros()` are very intuitively, they create arrays full of ones and zeros respectively. The amount of elements in the arrays are determined by the integer we pass as an argument. 

In [4]:
numpy.ones(5)

array([ 1.,  1.,  1.,  1.,  1.])

In [5]:
numpy.zeros(3)

array([ 0.,  0.,  0.])

`numpy.arange()` gives as an evenly spaced values in a defined interval. 

*Syntax:*

`numpy.arange(start, stop, step)`

where `start` by default is zero, `stop` is not inclusive, and the default
for `step` is one.  


In [6]:
numpy.arange(4)

array([0, 1, 2, 3])

In [7]:
numpy.arange(2, 6)

array([2, 3, 4, 5])

In [19]:
numpy.arange(2, 6, 2)

array([2, 4])

In [20]:
numpy.arange(2, 6, 0.5)

array([ 2. ,  2.5,  3. ,  3.5,  4. ,  4.5,  5. ,  5.5])

`numpy.linspace()` is similar to `numpy.arange()`, but uses number of samples instead of a step size. 

`numpy.linspace()` returns an array with evenly spaced numbers over the specified interval.  

*Syntax:*

`numpy.linspace(start, stop, num)`

`stop` is included by default (it can be removed, read docs) and `num` by default is 50. 

In [12]:
numpy.linspace(2.0, 3.0)

array([ 2.        ,  2.02040816,  2.04081633,  2.06122449,  2.08163265,
        2.10204082,  2.12244898,  2.14285714,  2.16326531,  2.18367347,
        2.20408163,  2.2244898 ,  2.24489796,  2.26530612,  2.28571429,
        2.30612245,  2.32653061,  2.34693878,  2.36734694,  2.3877551 ,
        2.40816327,  2.42857143,  2.44897959,  2.46938776,  2.48979592,
        2.51020408,  2.53061224,  2.55102041,  2.57142857,  2.59183673,
        2.6122449 ,  2.63265306,  2.65306122,  2.67346939,  2.69387755,
        2.71428571,  2.73469388,  2.75510204,  2.7755102 ,  2.79591837,
        2.81632653,  2.83673469,  2.85714286,  2.87755102,  2.89795918,
        2.91836735,  2.93877551,  2.95918367,  2.97959184,  3.        ])

In [13]:
len(numpy.linspace(2.0, 3.0))

50

In [17]:
numpy.linspace(2.0, 3.0, 6)

array([ 2. ,  2.2,  2.4,  2.6,  2.8,  3. ])

In [22]:
numpy.linspace(-1, 1, 9)

array([-1.  , -0.75, -0.5 , -0.25,  0.  ,  0.25,  0.5 ,  0.75,  1.  ])

Let's assign the arrays to some variables and perform some operations. 

In [ ]:
x_array = numpy.linspace(-1, 1, 9)

In [2]:
# Execute this cell to load the notebook's style sheet, then ignore it
from IPython.core.display import HTML
css_file = '../../style/custom.css'
HTML(open(css_file, "r").read())